# Generated by Django 3.0.3 on 2020-10-20 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='registered_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
